FROM golang:1.17 as build
WORKDIR /jwt-practice
COPY main.go /jwt-practice
COPY go.mod /jwt-practice
COPY go.sum /jwt-practice
RUN CGO_ENABLED=0 GOOS=linux go build -installsuffix cgo -o ./app .

FROM registry.access.redhat.com/ubi8:latest
COPY --from=0 /jwt-practice/app .
EXPOSE 8080
CMD ["/app"]